### ISSUE TITLE
Every time that you change form Advance to Simple, the second entity button remains in the top.

### ISSUE THREAD

**Issue by molyom** [DigitalFlow/D365-PowerKanban#23] opened 2020-08-19 15:14 UTC
![image](https://user-images.githubusercontent.com/12083302/90653414-6eec0500-e23f-11ea-9ea6-fe1c72e42edf.png)

**Comment by DigitalFlow** [comment] 2020-08-20 10:51
Hi @molyom,

please try v0.9.12, should be fixed there.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment] 2020-08-21 08:11
Hi @molyom,

I'll close this issue, if the issue is not fixed for you in the latest version, please reopen.

Kind Regards,
Florian

**Closed by DigitalFlow** 2020-08-21 08:11 UTC

**Comment by molyom** [comment] 2020-08-21 08:14
Fiexd. Thanks
